In [1]:
# ============================================================
# dask_pipeline.ipynb
# Dask ML Pipeline - NYC Taxi Dataset
# ============================================================

# 1. Imports

import time

import requests
import dask.dataframe as dd
import numpy as np
import pandas as pd

from glob import glob

from pydantic import ByteSize
from dask.distributed import Client
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from dask_ml.model_selection import KFold, train_test_split
from sklearn.metrics import make_scorer

from dask_ml.model_selection import train_test_split
from dask_ml.linear_model import LogisticRegression as DaskLogisticRegression
from xgboost.dask import DaskXGBRegressor

from datetime import timedelta

from collections.abc import Generator
from contextlib import contextmanager
from datetime import timedelta
from pathlib import Path
from time import perf_counter
from typing import TypedDict

from pathlib import Path

In [2]:
# 2. Start Dask client

# client = Client(
#     n_workers=5,
#     threads_per_worker=2

# )
WORKERS = 1
THREADS_PER_WORKER = 32
MEMORY_LIMIT = "64GB"

client = Client(
    n_workers=WORKERS,
    threads_per_worker=THREADS_PER_WORKER,
    memory_limit=MEMORY_LIMIT
)

client

In [3]:
# 3. Configuration


DATA_PATH =  sorted(glob("../data/raw/taxi/2024/yellow_tripdata_2024-0[1-3].parquet"))
LOOKUP_PATH = "../data/raw/taxi/taxi_zone_lookup.csv"

SOURCE_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet"

TARGET = "fare_amount"

FEATURES = [
    "trip_distance",
    "passenger_count",
    "PULocationID",
    "DOLocationID",
    "payment_type",
]

SEED = 42
TEST_SIZE = 0.2

CLASSIFICATION_CV_FOLDS = 5
REGRESSION_CV_FOLDS = 5

LOGISTIC_MAX_ITER = 100
LOGISTIC_REGULARIZATION = 0.0

XGB_N_ESTIMATORS = 100
XGB_MAX_DEPTH = 6

XGB_LEARNING_RATE = 0.1

RESULTS_PATH = f"../results/One-year/{WORKERS}_workers_{THREADS_PER_WORKER}_threads_{MEMORY_LIMIT}/dask_benchmark_results.csv"

In [4]:
class Duration(TypedDict):
    duration: timedelta


def _mem_str(path: str) -> str:
    path = Path(path)
    size = path.stat().st_size
    return ByteSize(size).human_readable(decimal=True)

@contextmanager
def timeit(name: str) -> Generator[dict]:
    result = {"duration": timedelta()}
    start_time = perf_counter()
    yield result
    end_time = perf_counter()
    duration = timedelta(seconds=end_time - start_time)
    print(f"{name} took {duration}")
    result["duration"] = duration

In [5]:
# 4. Load data
df: dd.DataFrame = None
try:
    with timeit("Loading data"):
        df = dd.read_parquet(DATA_PATH)
except FileNotFoundError:
    response = requests.get(SOURCE_URL)
    response.raise_for_status()
    Path(DATA_PATH).parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_PATH, "wb") as f:
        f.write(response.content)
    print(f"Downloaded {DATA_PATH}, {_mem_str(DATA_PATH)}")
    with timeit("Loading data"):
        df = dd.read_parquet(DATA_PATH)


location_lookup = dd.read_csv("../data/raw/taxi/taxi_zone_lookup.csv")


df.tail()

Loading data took 0:00:00.009368

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
2964619,2,2024-01-31 23:45:59,2024-01-31 23:54:36,NaN,3.18,NaN,<NA>,107,263,0,15.77,0.00,0.5,2.00,0.00,1.0,21.77,NaN,NaN
2964620,1,2024-01-31 23:13:07,2024-01-31 23:27:52,NaN,4.00,NaN,<NA>,114,236,0,18.40,1.00,0.5,2.34,0.00,1.0,25.74,NaN,NaN
2964621,2,2024-01-31 23:19:00,2024-01-31 23:38:00,NaN,3.33,NaN,<NA>,211,25,0,19.97,0.00,0.5,0.00,0.00,1.0,23.97,NaN,NaN
2964622,2,2024-01-31 23:07:23,2024-01-31 23:25:14,NaN,3.06,NaN,<NA>,107,13,0,23.88,0.00,0.5,5.58,0.00,1.0,33.46,NaN,NaN
2964623,1,2024-01-31 23:58:25,2024-02-01 00:13:30,NaN,8.10,NaN,<NA>,138,75,0,32.40,7.75,0.5,7.29,6.94,1.0,55.88,NaN,NaN

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.0
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.0

In [7]:
# 5. Basic dataset inspection

print("Columns:")
print(df.columns)

print("Dtypes:")
print(df.dtypes)

print("Number of partitions:")
print(df.npartitions)

Columns:
Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee'],
      dtype='str')
Dtypes:
VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                   int64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag               string
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
dtype: object
Number of partitions:
1

In [8]:
# 6. Preprocessing

df = df[FEATURES + [TARGET]]
df = df.dropna()
df = df[
    (df["fare_amount"] > 0) &
    (df["trip_distance"] > 0) &
    (df["passenger_count"] > 0)
]

df = df.repartition(npartitions=3)
df = df.reset_index(drop=True)
df = df.clear_divisions()

df.tail()

,trip_distance,passenger_count,PULocationID,DOLocationID,payment_type,fare_amount
0,7.68,1.0,230,243,1,31.0
1,3.51,1.0,138,129,1,16.3
2,3.36,1.0,162,261,1,18.4
3,3.30,3.0,43,249,1,17.7
4,1.58,1.0,140,263,1,8.6

In [9]:
def benchmark_dask(data_path, lookup_path):
    metrics = {}

    # 1. Read Data
    with timeit("1. Read Data") as duration:
        df = dd.read_parquet(data_path)
        df_lookup = dd.read_csv(lookup_path) # estamos a fazer leitura desse ficheiro para a operação de join/merge
        df_lookup["LocationID"] = df_lookup["LocationID"].astype(df["PULocationID"].dtype)
        # Dask reads lazily; force compute on length to evaluate reading execution
        _ = len(df)
    metrics['1. Read Data'] = duration["duration"]

    # 2. Count Index (Simple count)
    with timeit("2. Count Operation") as duration:
        _ = df.count().compute()
    metrics['2. Count Operation'] = duration["duration"]

    # 3. Complex Arithmetic Formula
    with timeit("3. Complex Arithmetic") as duration:
        arithmetic_res = (df['fare_amount'] + df['tip_amount']) * 1.5 / (df['passenger_count'] + 1)
        _ = arithmetic_res.compute()
    metrics['3. Complex Arithmetic'] = duration["duration"]

    # 4. Statistical Standard Deviation
    with timeit("4. Standard Deviation") as duration:
        _ = df['trip_distance'].std().compute()
    metrics['4. Standard Deviation'] = duration["duration"]

    # 5. GroupBy Aggregation
    with timeit("5. GroupBy Mean") as duration:
        _ = df.groupby('passenger_count')['fare_amount'].mean().compute()
    metrics['5. GroupBy Mean'] = duration["duration"]

    # 6. Merge/Join with Count
    with timeit("6. Join & Count") as duration:
        joined = dd.merge(df, df_lookup, left_on='PULocationID', right_on='LocationID', how='inner')
        _ = len(joined)
    metrics['6. Join & Count'] = duration["duration"]

    return metrics

In [10]:
benchmarks = benchmark_dask(DATA_PATH, LOOKUP_PATH)

1. Read Data took 0:00:00.014041
2. Count Operation took 0:00:00.439115
3. Complex Arithmetic took 0:00:00.167295
4. Standard Deviation took 0:00:00.106926
5. GroupBy Mean took 0:00:00.103168
6. Join & Count took 0:00:00.175628

In [11]:
X = df[FEATURES]
y_reg = df[TARGET]

X_train, X_test, y_train_reg, y_test_reg = train_test_split(
    X,
    y_reg,
    test_size=TEST_SIZE,
    random_state=SEED,
    shuffle=True
)

#Specific for one year data :
X_train = X_train.repartition(npartitions=12)
X_test = X_test.repartition(npartitions=12)

y_train_reg = y_train_reg.repartition(npartitions=12)
y_test_reg = y_test_reg.repartition(npartitions=12)

X_train_arr = X_train.to_dask_array(lengths=True)
X_test_arr = X_test.to_dask_array(lengths=True)

y_train_reg_arr = y_train_reg.to_dask_array(lengths=True)
y_test_reg_arr = y_test_reg.to_dask_array(lengths=True)

reg_model = DaskXGBRegressor(
    n_estimators=XGB_N_ESTIMATORS,
    max_depth=XGB_MAX_DEPTH,
    learning_rate=XGB_LEARNING_RATE,
    objective="reg:squarederror",
    random_state=SEED
)

reg_cv = KFold(
    n_splits=REGRESSION_CV_FOLDS,
    shuffle=True,
    random_state=SEED
)

reg_cv_rmse_scores = []

with timeit("Regression cross-validation") as duration:
    for train_idx, val_idx in reg_cv.split(X_train_arr):
        X_fold_train = X_train_arr[train_idx]
        X_fold_val = X_train_arr[val_idx]

        y_fold_train = y_train_reg_arr[train_idx]
        y_fold_val = y_train_reg_arr[val_idx]

        fold_model = DaskXGBRegressor(
            n_estimators=XGB_N_ESTIMATORS,
            max_depth=XGB_MAX_DEPTH,
            learning_rate=XGB_LEARNING_RATE,
            objective="reg:squarederror",
            random_state=SEED
        )

        fold_model.fit(X_fold_train, y_fold_train)

        y_fold_pred = fold_model.predict(X_fold_val).compute()
        y_fold_val_local = y_fold_val.compute()

        fold_rmse = mean_squared_error(
            y_fold_val_local,
            y_fold_pred
        ) ** 0.5

        reg_cv_rmse_scores.append(fold_rmse)

regression_cv_time = duration["duration"]
regression_cv_rmse_mean = np.mean(reg_cv_rmse_scores)
regression_cv_rmse_std = np.std(reg_cv_rmse_scores)

print("Regression CV RMSE scores:", reg_cv_rmse_scores)
print("Mean RMSE:", regression_cv_rmse_mean)
print("Std RMSE:", regression_cv_rmse_std)

with timeit("Regression training") as duration:
    fitted_reg_model = reg_model.fit(
        X_train_arr,
        y_train_reg_arr
    )

regression_train_time = duration["duration"]

with timeit("Regression prediction") as duration:
    y_pred_reg = fitted_reg_model.predict(X_test_arr).compute()

regression_prediction_time = duration["duration"]

y_test_reg_local = y_test_reg_arr.compute()

/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask/array/slicing.py:1029: PerformanceWarning: Increasing number of chunks by factor of 10
  p = blockwise(
[14:49:58] Task [xgboost.dask-0]:tcp://127.0.0.1:37319 got rank 0
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask/array/slicing.py:1029: PerformanceWarning: Increasing number of chunks by factor of 11
  p = blockwise(
[14:50:08] Task [xgboost.dask-0]:tcp://127.0.0.1:37319 got rank 0
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask/array/slicing.py:1029: PerformanceWarning: Increasing number of chunks by factor of 10
  p = blockwise(
[14:50:13] Task [xgboost.dask-0]:tcp://127.0.0.1:37319 got rank 0
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask/array/slicing.py:1029: PerformanceWarning: Increasing number of chunks by factor of 11
  p = blockwise(
[14:50:20] Task [xgboost.dask-0]:tcp://127.0.0.1:37319 got rank 0
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask/array/slicing.py:1029: PerformanceWarning: Increasing number of chunks by factor of 10
  p = blockwise(
[14:50:26] Task [xgboost.dask-0]:tcp://127.0.0.1:37319 got rank 0

Regression cross-validation took 0:00:33.737058
Regression CV RMSE scores: [5.704332256029999, 5.162488667161042, 6.058117278817254, 5.093734146898058, 5.10814142531272]
Mean RMSE: 5.425362754843815
Std RMSE: 0.38933583490182055

[14:50:30] Task [xgboost.dask-0]:tcp://127.0.0.1:37319 got rank 0

Regression training took 0:00:04.228429
Regression prediction took 0:00:00.492526

In [12]:
regression_results = {
    "library": "Dask",
    "task": "regression",
    "model": "DaskXGBRegressor",
    "cv_folds": REGRESSION_CV_FOLDS,
    "cv_time": regression_cv_time,
    "cv_rmse_mean": regression_cv_rmse_mean,
    "cv_rmse_std": regression_cv_rmse_std,
    "train_time": regression_train_time,
    "prediction_time": regression_prediction_time,
    "mae": mean_absolute_error(y_test_reg_local, y_pred_reg),
    "mse": mean_squared_error(y_test_reg_local, y_pred_reg),
    "rmse": mean_squared_error(y_test_reg_local, y_pred_reg) ** 0.5,
    "r2": r2_score(y_test_reg_local, y_pred_reg),
}

In [ ]:
def classify_fare_partition(partition):
    return partition.assign(
        fare_class=np.select(
            [
                partition[TARGET] < 15,
                partition[TARGET] < 40,
            ],
            [0, 1],
            default=2
        )
    )


df_cls = df.map_partitions(classify_fare_partition)

X_cls = df_cls[FEATURES]
y_cls = df_cls["fare_class"]

X_train, X_test, y_train_cls, y_test_cls = train_test_split(
    X_cls,
    y_cls,
    test_size=TEST_SIZE,
    random_state=SEED,
    shuffle=True
)

X_train_arr = X_train.to_dask_array(lengths=True)
X_test_arr = X_test.to_dask_array(lengths=True)

y_train_arr = y_train_cls.to_dask_array(lengths=True)
y_test_arr = y_test_cls.to_dask_array(lengths=True)

cls_model = DaskLogisticRegression(
    max_iter=LOGISTIC_MAX_ITER,
    fit_intercept=True
)

#Cross Validation Models
cls_cv = KFold(

    n_splits=CLASSIFICATION_CV_FOLDS,
    shuffle=True,
    random_state=SEED

)

cls_cv_f1_scores = []

with timeit("Classification cross-validation") as duration:

    for train_idx, val_idx in cls_cv.split(X_train_arr):

        X_fold_train = X_train_arr[train_idx]
        X_fold_val = X_train_arr[val_idx]
        y_fold_train = y_train_arr[train_idx]
        y_fold_val = y_train_arr[val_idx]

        fold_model = DaskLogisticRegression(

            max_iter=LOGISTIC_MAX_ITER,
            fit_intercept=True

        )

        fold_model.fit(X_fold_train, y_fold_train)
        y_fold_pred = fold_model.predict(X_fold_val).compute()
        y_fold_val_local = y_fold_val.compute()

        fold_f1 = f1_score(

            y_fold_val_local,
            y_fold_pred,
            average="macro"

        )

        cls_cv_f1_scores.append(fold_f1)

classification_cv_time = duration["duration"]
classification_cv_f1_mean = np.mean(cls_cv_f1_scores)
classification_cv_f1_std = np.std(cls_cv_f1_scores)

print("Classification CV F1 scores:", cls_cv_f1_scores)
print("Mean F1:", classification_cv_f1_mean)
print("Std F1:", classification_cv_f1_std)

with timeit("Classification training") as duration:
    fitted_cls_model = cls_model.fit(X_train_arr, y_train_arr)

classification_train_time = duration["duration"]

with timeit("Classification prediction") as duration:
    y_pred_cls = fitted_cls_model.predict(X_test_arr).compute()

classification_prediction_time = duration["duration"]

y_test_cls_local = y_test_arr.compute()

/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)
/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/dask_glm/utils.py:66: RuntimeWarning: overflow encountered in exp
  return np.exp(A)

In [ ]:
classification_results = {
    "library": "Dask",
    "task": "classification",
    "model": "DaskLogisticRegression",
    "cv_folds": CLASSIFICATION_CV_FOLDS,
    "cv_time": classification_cv_time,
    "cv_f1_macro_mean": classification_cv_f1_mean,
    "cv_f1_macro_std": classification_cv_f1_std,
    "train_time": classification_train_time,
    "prediction_time": classification_prediction_time,
    "accuracy": accuracy_score(y_test_cls_local, y_pred_cls),
    "precision_macro": precision_score(y_test_cls_local, y_pred_cls, average="macro"),
    "recall_macro": recall_score(y_test_cls_local, y_pred_cls, average="macro"),
    "f1_macro": f1_score(y_test_cls_local, y_pred_cls, average="macro"),
}

/home/caio/uporto/bigdata/assign2/bdcc-project2/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
#Save Results

benchmark_results_df = pd.DataFrame([
    {
        "library": "Dask",
        "operation": operation,
        "duration": duration,
        "duration_seconds": duration.total_seconds()
    }

    for operation, duration in benchmarks.items()
])

Path(RESULTS_PATH).parent.mkdir(parents=True, exist_ok=True)
benchmark_results_df.to_csv(RESULTS_PATH,index=False)

results_df = pd.DataFrame([
    regression_results,
    classification_results
])

results_df.to_csv("../results/One-year/dask_pipeline_results.csv", index=False)

results_df

,library,task,model,cv_folds,cv_time,cv_rmse_mean,cv_rmse_std,train_time,prediction_time,mae,mse,rmse,r2,cv_f1_macro_mean,cv_f1_macro_std,accuracy,precision_macro,recall_macro,f1_macro
0,Dask,regression,DaskXGBRegressor,5,0 days 00:00:24.527446,5.425363,0.389336,0 days 00:00:03.662137,0 days 00:00:00.540108,2.147636,26.733053,5.170402,0.911134,NaN,NaN,NaN,NaN,NaN,NaN
1,Dask,classification,DaskLogisticRegression,5,0 days 00:08:30.806528,NaN,NaN,0 days 00:01:16.908288,0 days 00:00:00.319725,NaN,NaN,NaN,NaN,0.50278,0.015007,0.773125,0.490534,0.555382,0.518061

In [ ]:
client.close()